[workspace]
members = [
    "twilight-model"
]
resolver = "2"

[workspace.package]
authors = ["Twilight Contributors"]
edition = "2021"
include = ["src/**/*.rs", "README.md"]
license = "ISC"
repository = "https://github.com/twilight-rs/twilight.git"
rust-version = "1.67"
